<?xml version="1.0"?>
<!-- Copyright (c) 2016 The UUV Simulator Authors.
     All rights reserved.

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- includes -->
  <xacro:include filename="$(find uuv_descriptions)/urdf/common.urdf.xacro" />
  <xacro:include filename="$(find dave_snippets)/urdf/sensor_snippets.xacro"/>
  <xacro:include filename="$(find uuv_gazebo_ros_plugins)/urdf/snippets.xacro"/>

  <!-- Properties -->
  <!-- ToDo: Properties need to be updated -->
  <xacro:property name="mass" value="50.0" />
  <xacro:property name="length" value="1.5" />
  <xacro:property name="diameter" value="0.22" />
  <xacro:property name="radius" value="${diameter*0.5}" />
  <xacro:property name="volume" value="0.06799987704121499" />

  <!-- Center of buoyancy -->
  <xacro:property name="cob" value="0 0 0.06" />

  <!-- Center of gravity -->
  <xacro:property name="cog" value="0 0 0" />

  <!-- Fluid density -->
  <xacro:property name="rho" value="1027.0" /> 

  <xacro:property name="area" value="${diameter^2*3.141}" />

  <xacro:property name="namespace" value="glider_nautilus"/>
  <!-- ToDo: Mesh files need to be updated -->
  <xacro:property name="visual_mesh_file" value="file://$(find dave_robot_models)/models/glider_nautilus/mesh/Nautilus-Glider.dae" />
  <xacro:property name="collision_mesh_file" value="file://$(find dave_robot_models)/models/glider_nautilus/mesh/COLLISION-Nautilus-Glider.stl" />
  <!--<xacro:property name="prop_mesh_file" value="file://$(find dave_robot_models)/models/glider_slocum/mesh/Slocum-Glider-Propeller.dae" />-->
  <!-- <xacro:property name="rudder_mesh_file" value="file://$(find dave_robot_models)/models/glider_slocum/mesh/Slocum-Glider-TopRudder.dae" /> -->

  <xacro:macro name="glider_nautilus" params="namespace debug inertial_reference_frame">
    <link name="${namespace}/base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 -1.5708" />
        <geometry>
          <mesh filename="${visual_mesh_file}" scale="1 1 1" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 -1.5708" />
        <geometry>
          <mesh filename="${collision_mesh_file}" scale="1 1 1" />
        </geometry>
      </collision>
      <inertial>
        <mass value="${mass}"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="30.0" ixy="0" ixz="0" iyy="0.6" iyz="0" izz="5.0" />
      </inertial>
    </link>

    <!-- Set up hydrodynamic plugin -->
    <!-- ToDO: Get parameters for BCU -->
    <gazebo>
      <plugin name="${namespace}_uuv_plugin" filename="libuuv_underwater_object_ros_plugin.so">
        <fluid_density>${rho}</fluid_density>
        <flow_velocity_topic>hydrodynamics/current_velocity</flow_velocity_topic>
        <debug>${debug}</debug>
        <link name="${namespace}/base_link">
          <volume>${volume}</volume>
          <center_of_buoyancy>${cob}</center_of_buoyancy>
          <neutrally_buoyant>1</neutrally_buoyant>
          <hydrodynamic_model>
            <type>fossen</type>
            <added_mass>
              4   0   0   0   0   0
              0   95  0   0   0   0
              0   0   75  0   0   0
              0   0   0   0.4 0   0
              0   0   0   0   27  0
              0   0   0   0   0   32
            </added_mass>

            <linear_damping_forward_speed>
              -8      0       0       0       0       0
              0       -162    0       0       0       150
              0       0       -108    0       -100    0
              0       0       0       -13     0       0
              0       0       37      0       -20     0
              0       -34     0       0       0       -32
            </linear_damping_forward_speed>
          </hydrodynamic_model>
        </link>
      </plugin>
    </gazebo>

    <!-- Include the battery modules -->
    <!-- ToDO: Properties of battery required -->
    <xacro:basic_linear_battery_macro
      namespace="${namespace}"
      parent_link="${namespace}/base_link"
      prefix=""
      open_circuit_voltage_constant_coef="3.7"
      open_circuit_voltage_linear_coef="-3.1424"
      initial_charge="1.1665"
      capacity="0.5"
      resistance="0.002"
      smooth_current_tau="1.9499"
      voltage="4.2"
      update_rate="2.0"/>

    <!-- Include sensor modules -->
    <xacro:include filename="$(find glider_description)/urdf/glider_nautilus_sensors.xacro"/>
  </xacro:macro>


</robot>
